### ISSUE TITLE
Reference to this implementation of Newton's algorithm

### ISSUE THREAD

**Issue by Lysxia** [byorgey/boltzmann#1]
From `Oracle.Newton`'s name I assume that it implements some variant of Newton's algorithm in order to solve systems of generating functions. However it doesn't match the descriptions of the method I could find: to find a root of a multivariate function `f`, with jacobian `J`, iterate with `x(n+1) = x(n) - (J(x(n)) ^ -1) * f(x(n))`.

At first I thought the implementation was wrong, but it is more complicated than I thought (and I have trouble analyzing it), and more importantly it seems to find the solutions somehow. Can you point me to a reference for [this formula](https://github.com/byorgey/boltzmann/blob/master/gen/src/Oracle/Newton.hs#L52)?

**Comment by byorgey** [comment]
Good question!  I haven't actually looked carefully at that code yet (remember I did not originally write it).  I will take a look and see what I can figure out.

**Comment by maciej-bendkowski** [comment]
+1 for the question.

**Comment by maciej-bendkowski** [comment]
Just for reference, the optimization is presented in another [paper](https://arxiv.org/pdf/1109.2688v2.pdf) by the same authors. This should close this issue.

**Comment by byorgey** [comment]
Ah, thanks for the link to the paper.  Also, I actually wrote a [blog post asking about this](https://byorgey.wordpress.com/2016/06/20/any-clues-about-this-newton-iteration-formula-with-jacobian-matrix/) a while back, and the comments were super helpful (including a link to that paper, as well as some other things).  I just forgot to link it here.
